# Tokyo Night color scheme

foreground #a9b1d6
background #1a1b26

selection_foreground none
selection_background #28344a

# Cursor
cursor #c0caf5
cursor_text_color #1a1b26

# URL underline color when hovering
url_color #73daca

# Kitty window border colors
active_border_color   #7aa2f7
inactive_border_color #414868
bell_border_color     #e0af68

# OS Window titlebar colors
wayland_titlebar_color #1a1b26
macos_titlebar_color #1a1b26

# Tab bar colors
active_tab_foreground   #1a1b26
active_tab_background   #7aa2f7
inactive_tab_foreground #545c7e
inactive_tab_background #1a1b26
tab_bar_background      #15161e

# Marks
mark1_foreground #1a1b26
mark1_background #7aa2f7
mark2_foreground #1a1b26
mark2_background #bb9af7
mark3_foreground #1a1b26
mark3_background #7dcfff

# Black
color0 #15161e
color8 #414868

# Red
color1 #f7768e
color9 #f7768e

# Green
color2  #9ece6a
color10 #9ece6a

# Yellow
color3  #e0af68
color11 #e0af68

# Blue
color4  #7aa2f7
color12 #7aa2f7

# Magenta
color5  #bb9af7
color13 #bb9af7

# Cyan
color6  #7dcfff
color14 #7dcfff

# White
color7  #a9b1d6
color15 #c0caf5
