general {
    lock_cmd = pidof hyprlock || hyprlock       # Блокировка экрана
    before_sleep_cmd = loginctl lock-session    # Блокировка перед сном
    after_sleep_cmd = hyprctl dispatch dpms on  # Включение экрана после пробуждения
    ignore_dbus_inhibit = false                 # Учитывать D-Bus inhibit
}

# Предупреждение о бездействии
listener {
    timeout = 540                                           # 9 мин
    on-timeout = notify-send -u normal "💤 Idle" "Вы неактивны уже 9 минут"
    on-resume = notify-send -u low "👋 С возвращением!" "Привет!"
}

# Блокировка экрана
listener {
    timeout = 600                                           # 10 мин
    on-timeout = loginctl lock-session
}

# Выключение экрана
listener {
    timeout = 660                                           # 11 мин
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Засыпание системы (опционально)
listener {
    timeout = 1800                                          # 30 мин
    on-timeout = systemctl suspend
}