################
### MONITORS ###
################
monitor = eDP-1, 1920x1080@144, 0x0, 1
monitor = HDMI-A-1, 1920x1080@60, 1920x0, 1

###################
### MY PROGRAMS ###
###################
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$monitor = hyprctl dispatch workspace 1
$browser = brave
$vol = pamixer --get-volume
$cursor = hyprctl setcursor "macOS-White" 24

env = WLR_NO_HARDWARE_CURSORS,1

#################
### AUTOSTART ###
#################
exec-once = quickshell
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar & swaync
exec-once = $monitor & swww-daemon & $cursor & hypridle

exec-once = sh ~/.config/hypr/scripts/text_animation/anitext.sh
exec-once = sh ~/.config/hypr/scripts/weather/weather.sh


#############################
### ENVIRONMENT VARIABLES ###
#############################
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_MOVE, fleur


#####################
### LOOK AND FEEL ###
#####################
source= ~/.config/hypr/configs/looknfeel.conf

##################
### ANIMATIONS ###
##################
source= ~/.config/hypr/configs/UserAnimations.conf

##################################
### WINDOWRULES AND LAYERRULES ###
##################################
source = ~/.config/hypr/configs/windowrules.conf

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_status = master
}

misc {
    disable_hyprland_logo = true
    enable_swallow = true
    swallow_regex = ^(footclient|foot)$
    focus_on_activate = true
    mouse_move_enables_dpms = false
    vfr = true
    vrr = 0 
    animate_manual_resizes = false
    mouse_move_focuses_monitor = true
    disable_splash_rendering = true
}

debug {
    disable_logs = true
    disable_time = true
    damage_tracking=2
}

render {
	new_render_scheduling = true
}

#############
### INPUT ###
#############
source= ~/.config/hypr/configs/input.conf

################
### KEYBINDS ###
################
source= ~/.config/hypr/configs/keybinds.conf
