#############################
### ENVIRONMENT VARIABLES ###
#############################
source = ~/.config/hypr/configs/env.conf

################
### MONITORS ###
################
source = ~/.config/hypr/configs/monitors.conf

###################
### MY PROGRAMS ###
###################
source = ~/.config/hypr/configs/programs.conf

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/configs/autostart.conf

#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/configs/appearance.conf

##################   
### ANIMATIONS ###
##################
source = ~/.config/hypr/configs/animation.conf

##################################
### WINDOWRULES AND LAYERRULES ###
####################v##############
source = ~/.config/hypr/configs/windowrules.conf

#############
### INPUT ###
#############
source = ~/.config/hypr/configs/input.conf

################
### KEYBINDS ###
################
source = ~/.config/hypr/configs/keybinds.conf

##############
### LAYOUT ###
##############
source = ~/.config/hypr/configs/layout.conf

##################
### CURSOR FIX ###
##################
cursor {
    no_hardware_cursors = true
    enable_hyprcursor = true
    use_cpu_buffer = true
    #hide_on_key_press = false
    #inactive_timeout = 0
}

############
### MISC ###
############
source = ~/.config/hypr/configs/misc.conf

##############
### RENDER ###
##############
render {
    new_render_scheduling = true
    #direct_scanout = true
}

###############
### OPENGL ###
###############
opengl {
    #nvidia_anti_flicker = true
}

#################
### BINDS FIX ###
#########s########
binds {
    # Улучшает отзывчивость при использовании биндов
    workspace_back_and_forth = false
    allow_workspace_cycles = true
    pass_mouse_when_bound = false
}



