# ██╗███╗   ██╗██████╗ ██╗   ██╗████████╗
# ██║████╗  ██║██╔══██╗██║   ██║╚══██╔══╝
# ██║██╔██╗ ██║██████╔╝██║   ██║   ██║   
# ██║██║╚██╗██║██╔═══╝ ██║   ██║   ██║   
# ██║██║ ╚████║██║     ╚██████╔╝   ██║   
# ╚═╝╚═╝  ╚═══╝╚═╝      ╚═════╝    ╚═╝   
#----------------------------------------

input {
    kb_layout = us, ru
    kb_options = grp:win_space_toggle
    follow_mouse = 1
    sensitivity = 0
    mouse_refocus = true
    float_switch_override_focus = 2

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
    }
}

gesture = 3, horizontal, workspace

