# ███╗   ███╗██╗███████╗ ██████╗
# ████╗ ████║██║██╔════╝██╔════╝
# ██╔████╔██║██║███████╗██║     
# ██║╚██╔╝██║██║╚════██║██║     
# ██║ ╚═╝ ██║██║███████║╚██████╗
# ╚═╝     ╚═╝╚═╝╚══════╝ ╚═════╝
#-------------------------------

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    
    # VRR/VFR для 144Hz монитора
    vfr = true
    #vrr = 1
    
    # DPMS (энергосбережение)
    #mouse_move_enables_dpms = true
    #key_press_enables_dpms = true
    
    # Производительность
    #animate_manual_resizes = false
    #animate_mouse_windowdragging = false
    
    # Фокус
    #focus_on_activate = true
    
    # Улучшения для работы
    #middle_click_paste = false
    #allow_session_lock_restore = true
}